### ISSUE TITLE
Julia wrapper of bocop for benchmarking

### ISSUE THREAD

**Issue by ocots** [control-toolbox/OptimalControl.jl#119]
Make a julia wrapper of bocop for benchmarking. Done on the bocop repo. Julia package 'bocop' provides functions to build and run bocop executables, and read solution files. 
Todo: 
- [ ] proper release of the package.
- [ ] benchmark script

**Comment by PierreMartinon** [comment]
Done on the bocop repo. Julia package 'bocop' provides functions to build and run bocop executables, and read solution files. Todo: proper release of the package.
