### ISSUE TITLE
Common optimal control solution

### ISSUE THREAD

**Issue by ocots** [control-toolbox/OptimalControl.jl#120]
Add a general optimal control solution to define a common plot and to use as init of the direct methods.

* [x] create an `OptimalControlSolution` in `CTBase`
* [x] create a plot function for the optimal control solution
* [x] add initialization from an `OptimalControlSolution` in `CTDirectShooting`
* [ ] add initialization from an `OptimalControlSolution` in `CTDirect`
* [ ] add post-treatment / diagnosis of a given solution. See #131

**Comment by ocots** [comment]
* Create an `OptimalControlInit` and different constructors.
* To `CTDirect` and `CTDirectShooting` solve, the only init we can pass will be an `OptimalControlInit`.
* To `OptimalControl` solve, we can pass many different kind of init, used to construct an `OptimalControlInit` which will be given to the solver.

**Comment by PierreMartinon** [comment]
Added state constraints and their multipliers in the 'infos' dict of the solution struct.
Todo: control/mixed constraints, then later multipliers for box constraints (need to be parsed)
