### ISSUE TITLE
Rethink package purpose 

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#134]
role of package *vs.* `CTBase.jl` has been shifting a bit. must rethink. as the root package of the ecosystem, should provide
- definition
- solve
- plot

for an ocp.

**Comment by ocots** [comment]
I think it is important that `OptimalControl` exports only what we want the user to have. For the moment, we reexport everything, cf.

```julia
module OptimalControl

# using
using Reexport

# include modules
@reexport using CTBase
using CTDirect
using CTDirectShooting

# flows
@reexport using CTFlows

# Other declarations
const __display = CTBase.__display

# resources
include("solve.jl")

# export functions only for user
export solve

end
```

**Comment by ocots** [comment]
The package `OptimalControl.jl` selects the different methods we can use:

```julia
algorithmes = add(algorithmes, (:direct, :ADNLProblem, :ipopt))
algorithmes = add(algorithmes, (:direct, :shooting, :descent, :bfgs, :bissection))
algorithmes = add(algorithmes, (:direct, :shooting, :descent, :bfgs, :backtracking))
algorithmes = add(algorithmes, (:direct, :shooting, :descent, :bfgs, :fixedstep))
algorithmes = add(algorithmes, (:direct, :shooting, :descent, :gradient, :bissection))
algorithmes = add(algorithmes, (:direct, :shooting, :descent, :gradient, :backtracking))
algorithmes = add(algorithmes, (:direct, :shooting, :descent, :gradient, :fixedstep))
```

**Comment by jbcaillau** [comment]
Very nice graph! A bit puzzled by `OptimalControl.jl` being at the bottom of this not-a-tree graph. To be discussed.

**Comment by ocots** [comment]
It is just markdown.

**Comment by ocots** [comment]
We need also a mechanism for initialization. The user should provide different kind of init, then `OptimalControl.jl` transforms it to one type of init and then pass it to the solver.
