### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by ocots** [control-toolbox/OptimalControl.jl#166]
Need to think about how to be cited. See [this example](https://docs.sciml.ai/Optimization/stable/#Citation) via Zenodo.

**Comment by jbcaillau** [comment]
Closing in favour of https://github.com/control-toolbox/OptimalControl.jl/issues/175

**Comment by jbcaillau** [comment]
Closing in favour of https://github.com/control-toolbox/OptimalControl.jl/issues/175
