### ISSUE TITLE
Export CTDirect functions

### ISSUE THREAD

**Issue by ocots** [control-toolbox/OptimalControl.jl#167]
Do not forget for the next release to export useful functions from the `CTDirect.jl` package.

**Comment by ocots** [comment]
@PierreMartinon In `OptimalControl.jl`, do we export all the useful functions from `CTDirect.jl`?

**Comment by PierreMartinon** [comment]
> @PierreMartinon In `OptimalControl.jl`, do we export all the useful functions from `CTDirect.jl`?

The new tutorials will help to check this. The ones for initial guess and continuation cover the most common uses, I guess we only have the NLP/DOCP handling left. I can start a basic tutorial with just function calls, upon which @jbcaillau can expand.

**Comment by PierreMartinon** [comment]
New exports can be seen in the draft PR https://github.com/control-toolbox/OptimalControl.jl/pull/203
