### ISSUE TITLE
Move initial guess + continuation tuto from CTDirect to OptimalControl

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#170]
@PierreMartinon The title is clear 🙂
- [initial guess](https://control-toolbox.org/docs/ctdirect/stable/tutorial.html)
- [continuation](https://control-toolbox.org/docs/ctdirect/stable/continuation.html)

More or less only keep API + dev info in subpackages docs.

**Comment by jbcaillau** [comment]
@PierreMartinon can you please move [this tuto](https://control-toolbox.org/CTDirect.jl/stable/tutorial.html#Initial-guess-options) from CTDirect.jl to OptimalControl.jl? (Where this [tuto](https://control-toolbox.org/docs/optimalcontrol/stable/tutorial-init.html) is outdated: "no warm start...")

More generally, I advocate having API and details for developers in the CTxxxx.jl repos, tutorials for users in one place that is OptimalControl.jl.

Your thoughts on this? @ocots @gergaud ?

**Comment by PierreMartinon** [comment]
I'll start a branch on this. By the way, as far as I know the docs/dev pages are only updated on the main branch, so is there a way to check the new docs apart from building them locally ?

**Comment by ocots** [comment]
- You can test locally.
- When it is on the `main` branch, then the doc is placed in `dev`: https://control-toolbox.org/OptimalControl.jl/dev/
- When we make a new release in github, the doc is place in `stable`: https://control-toolbox.org/OptimalControl.jl/stable/
- When I aggregate all the docs, then it is placed here: https://control-toolbox.org/docs/optimalcontrol

No more possibilities.

**Comment by ocots** [comment]
In [this tutorial](https://control-toolbox.org/CTDirect.jl/dev/tutorial.html#Initial-guess-options), there are several things:

1. The definition of the Goddard problem with its basic resolution.
2. The initial guess options with warm start strategy.
3. Advanced usage with the direct transcription.

The first point is already presented [here](https://control-toolbox.org/docs/optimalcontrol/stable/tutorial-goddard.html).

The second point could be merged with [this tutorial](https://control-toolbox.org/docs/optimalcontrol/stable/tutorial-init.html). I think we must not show to the user the `OCPInit` function. In the tutorial, we should make some sections: 

- constant initial guess (this is presented in both tutorials and can be merged)
- functions of time for the initialization (this is presented in both tutorials and can be merged)
- mixed of the two previous cases (this is only on @PierreMartinon tutorial)
- warm start strategy (this is only on @PierreMartinon tutorial)

**Remark.** For consistency with `OptimalControlModel`, `OptimalControlSolution`,  we should replace `OCPInit` by `OptimalControlInit`.

For the third point, I think that it is a more advanced usage. I recommend to put this in another tutorial. This new tutorial can reference the one about initialization if it is useful. We can imagine a tutorial about manipulations of the "discretized problem".

**Comment by ocots** [comment]
The tutorial about discrete continuation can be also moved to `OptimalControl.jl`.

I would suggest to keep only abstract formulations of optimal control problems. But, we could keep the part that explains how to remove and replace a constraint instead of redefining all the problem.

**Remark.** [Here](https://github.com/control-toolbox/HMP/blob/main/main.ipynb) I have an example of a discrete continuation with storage of the solutions and plottings. I think we could in the same spirit show a nice evolution with well chosen plots for a well chosen problem.

**Comment by ocots** [comment]
The two tutorials have been moved to `OptimalControl.jl` by @PierreMartinon. Consider as done.
