### ISSUE TITLE
Go to general registry

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#171]
@ocots @PierreMartinon @gergaud 
- deadlines: [FGS](https://www.unioviedo.es/fgs2024) June 18, [JuliaCon2024](https://juliacon.org/2024) July 8
- OptimalControl.jl version 1.0?
- what do we *absolutely* want to be in the package when going in?

**Comment by jbcaillau** [comment]
Ongoing https://github.com/JuliaRegistries/General/pull/110480

**Comment by PierreMartinon** [comment]
In CTDirect I don't think we can get the general RK scheme in time.
So maybe just focus on tidying up the docs, tests and fixing the occasional bug.

**Comment by jbcaillau** [comment]
> In CTDirect I don't think we can get the general RK scheme in time. So maybe just focus on tidying up the docs, tests and fixing the occasional bug.

Yes indeed. No hurry for RK schemes.

**Comment by jbcaillau** [comment]
@ocots on registering a package in general while it has dependencies towards a local registry https://github.com/JuliaLang/Pkg.jl/issues/810

**Comment by jbcaillau** [comment]
@ocots might be safer to edit the graph in https://github.com/JuliaRegistries/General/pull/110480#issuecomment-2210531425 and remove the mention to `CTProblems.jl` to avoid further confusion.

**Comment by jbcaillau** [comment]
@ocots https://github.com/JuliaRegistries/General/pull/110480#issuecomment-2211960859
