### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#172]
WIP (not yet ready for the release)
~~@ocots can you please make a new release to include updates in~~
- [CTDirect.jl](https://github.com/control-toolbox/CTDirect.jl/issues/88#issuecomment-2125850857)
- [CTBase.jl](https://github.com/control-toolbox/CTBase.jl/pull/136) (1/2)
- [CTBase.jl](https://github.com/control-toolbox/CTBase.jl/pull/132) (2/2) ?

**Comment by PierreMartinon** [comment]
I'll bump CTDirect to 0.5.1 soon to take into account the latest patch that solved the SymbolicUtils problem.

**Comment by jbcaillau** [comment]
@ocots Ready to merge. Note that:
- I have suppressed divisions of the Lagrange part, and more generally explicitly send an error for this kind of (forbidden) Lagrange declarations (interpreted as Mayer ones):
```julia
 @test_throws ParsingError @def o begin
        t ∈ [ t0, tf ], time
        x ∈ R^2, state
        u ∈ R, control
        x(t0) == [ -1, 0 ], (1)
        x(tf) == [  0, 0 ]
        ẋ(t) == A * x(t) + B * u(t)
        ∫( u(t)^2 ) + 1 + 2 → min # should be ∫(...) + ( 1 + 2 )
    end

    @test_throws ParsingError @def o begin
        t ∈ [ t0, tf ], time
        x ∈ R^2, state
        u ∈ R, control
        x(t0) == [ -1, 0 ], (1)
        x(tf) == [  0, 0 ]
        ẋ(t) == A * x(t) + B * u(t)
        ∫( u(t)^2 ) / 2 → min # forbidden
    end
```
- debatable for division but: not very useful and pollutes a bit the grammar
- also suppressed (old todo) implicit dimension declarations for variable, state and control (giving no dimension would mean dimension `== 1`)

**Comment by ocots** [comment]
Merge done!

**Comment by jbcaillau** [comment]
> I'll bump CTDirect to 0.5.1 soon to take into account the latest patch that solved the SymbolicUtils problem.

@PierreMartinon new release please!

**Comment by jbcaillau** [comment]
> Merge done!

@ocots CTBase.jl 0.8.0 -> 0.9.0?

**Comment by ocots** [comment]
> > Merge done!
> 
> @ocots CTBase.jl 0.8.0 -> 0.9.0?

Done!

**Comment by jbcaillau** [comment]
@ocots seems to be a compat issue (with CTProblems!?) that prevents update towards CTBase@0.9.0 in OptimalControl. Can you please have a look?

**Comment by PierreMartinon** [comment]
I will update CTDirect to require CTBase 0.9 (currently it stays at 0.8) as soon as the CI passes. This will be 0.5.2 I guess

**Comment by ocots** [comment]
OK I check this.

**Comment by ocots** [comment]
New release of `OptimalControl.jl`! 

`v0.8.0`

**Comment by ocots** [comment]
Old and finished.
