### ISSUE TITLE
Package extensions

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#179]
@ocots @PierreMartinon @joseph-gergaud should avoid using (and precompiling)
- optim solvers (update CTDirect)
- ODE solvers (update CTFlow)
- plot backends (update CTFlow)

From 1.9, use [](https://docs.julialang.org/en/v1/manual/code-loading/#man-extensions) rather than [Requires.jl](https://github.com/JuliaPackaging/Requires.jl). See also [this talk](https://pretalx.com/juliacon2023/talk/YQQ9ZV/) at JuliaCon 2023.

**Comment by jbcaillau** [comment]
@amontoison any comment on Package extensions *vs.* Requires.jl?

**Comment by jbcaillau** [comment]
Regarding precompilation time, see also https://github.com/control-toolbox/OptimalControl.jl/issues/182

**Comment by jbcaillau** [comment]
@ocots current state of this change?

**Comment by PierreMartinon** [comment]
A nice simple example here: https://github.com/pebeto/julia_extensions_example/blob/main/ext/BaseAddExt.jl
I'll get started on ctdirect/nlpmodelipopt

**Comment by ocots** [comment]
In the toml I don't know what target is for?

**Comment by PierreMartinon** [comment]
Apparently it is used to set the test dependencies if you don't want a separate Project.toml in test/
(or more generally dependencies for a sub-directory)

https://stackoverflow.com/questions/73148553/what-is-the-purpose-of-extras-and-targets-in-a-julia-project-toml

**Comment by amontoison** [comment]
@ocots 
It was not possible to use a separate `Project.toml` in the `test` directory with older versions of Julia (≤ v1.1).
Many of us keep `[extras]` and `[targets]` to be able to test our packages on Julia v1.0 before that Julia v1.6 has become the new LTS version.
Since it still works nowadays, we don't update it unless necessary.

**Comment by jbcaillau** [comment]
> @ocots It was not possible to use a separate `Project.toml` in the `test` directory with older versions of Julia (≤ v1.1). Many of us keep `[extras]` and `[targets]` to be able to test our packages on Julia v1.0 before that Julia v1.6 has become the new LTS version. Since it still works nowadays, we don't update it unless necessary.

Good old fashioned julia boys 🥲

**Comment by ocots** [comment]
This has been done.

Extensions for Plots, DifferentialEquations and NLPModelsIpopt.
