### ISSUE TITLE
New release (CTDirect v0.7.0)

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#183]
@ocots @PierreMartinon looks like `CTDirect.jl` is now `v0.7.0`, including important updates on linear solvers (*): 
- the current version in `OptimalControl.jl` seems to be `v0.6.0`: update and new release?
- we need to be more accurate on our hierarchy of packages: the user only sees `OptimalControl.jl`, so an update in some `CTxxxx.jl` should be followed by some (cross)checks (there must indeed be tests in `OptimalControl.jl` itself) and update/new release. Am I missing sth?

(*) Specifically on this: I see in [this notebook](https://github.com/0Yassine0/COTS.jl/blob/main/Benchmark/GoddardModeles.ipynb) sth like
```julia
sol_ma27 = OptimalControl.solve(RocketOC,init=init,output_file="rocketOC.out",linear_solver="ma27",hsllib=HSL_jll.libhsl_path);
```

Is this documented somewhere?

**Comment by jbcaillau** [comment]
> @ocots @PierreMartinon looks like `CTDirect.jl` is now `v0.7.0`, including important updates on linear solvers (*):
> 
> * the current version in `OptimalControl.jl` seems to be `v0.6.0`: update and new release? 
> Is this documented somewhere?

check https://github.com/control-toolbox/CTDirect.jl/issues/69#issuecomment-2184081100

Plus `CTBase` now on `v0.10`

**Comment by jbcaillau** [comment]
@ocots I thought you had updated to `CTFlows.jl v0.4` in here, but not there: waiting to update the doc https://github.com/control-toolbox/OptimalControl.jl/issues/187?

**Comment by ocots** [comment]
A new release of `OptimalControl` will be done after the following branch is merged: #187.

Need to update the documentation first. The new release will have in its compat:

- CTBase = 0.10
- CTDirect = 0.7
- CTFlows = 0.4
- CTProblems = 0.7

**Comment by PierreMartinon** [comment]
The next release with the package extensions typically requires *using NLPModelsIpopt, HSL* if you want to call the *solve*. Do you prefer v0.8.0 or v0.7.2 ?

**Comment by jbcaillau** [comment]
@ocots @PierreMartinon closing in favour of https://github.com/control-toolbox/OptimalControl.jl/issues/187
