### ISSUE TITLE
`OptimalControl.jl` upgrade: `CTBase.jl` `v0.10`, `CTFlows.jl` `v0.4`, `CTDirect.jl` `v0.7`, `CTProblems.jl` `v0.7`

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#187]
> > The CI is ok but we need to update all the tutorials.
> 
> @ocots can you please elaborate a bit?

- [Basic example](https://control-toolbox.org/docs/optimalcontrol/dev/tutorial-basic-example.html): add `using Plots`, remove `size` kwarg in plot function.
- [Basic example functional](https://control-toolbox.org/docs/optimalcontrol/dev/tutorial-basic-example-f.html): add `using Plots`, remove `size` kwarg in plot function. Update the definition of the ocp from the new API.
- [Double integrator: time minimisation](https://control-toolbox.org/docs/optimalcontrol/dev/tutorial-double-integrator.html): add `using Plots`, remove `size` kwarg in plot function.
- [Initial guess](https://control-toolbox.org/docs/optimalcontrol/dev/tutorial-init.html): update the tutorial according to https://github.com/control-toolbox/OptimalControl.jl/issues/170.
- [Plot a solution](https://control-toolbox.org/docs/optimalcontrol/dev/tutorial-plot.html): add info about series attributes, labelling, time normalisation.
- [LQR example](https://control-toolbox.org/docs/optimalcontrol/dev/tutorial-lqr-basic.html): add `using Plots`. Use the time normalisation within the plot function using `time=:normalized` instead of defining a rescaling function.
- [Indirect simple shooting](https://control-toolbox.org/docs/optimalcontrol/dev/tutorial-iss.html): add `using DifferentialEquations`, present `MINPACK` and `NonlinearSolver` (`MINPACK` cannot be used with arm).
- [Batch processing](https://control-toolbox.org/docs/optimalcontrol/dev/tutorial-batch.html): add `using Plots`, remove `size` kwarg in plot function. Add a label for the two plots using `solution_label` kwarg.
- [Goddard problem](https://control-toolbox.org/docs/optimalcontrol/dev/tutorial-goddard.html): add `using Plots`, remove `size` kwarg in plot function. Add a label for the two plots (`direct` and `indirect`) using `solution_label` kwarg. Add `using DifferentialEquations`. We can add a note on the fact that the user does not need to repeat `tf` when computing the flow, cf. this [issue](https://github.com/control-toolbox/CTFlows.jl/issues/15).

_Originally posted by @ocots in https://github.com/control-toolbox/OptimalControl.jl/issues/184#issuecomment-2186478224_

**Comment by jbcaillau** [comment]
@ocots @PierreMartinon wait for https://github.com/control-toolbox/CTDirect.jl/issues/115 to be solved, then update doc.

**Comment by ocots** [comment]
Par contre c'est dommage mais la branche https://github.com/control-toolbox/OptimalControl.jl/tree/187-doc-update vient de la `main` du coup on a perdu les trucs que j'avais modifié dans la branche `up`.

**Comment by jbcaillau** [comment]
> Par contre c'est dommage mais la branche https://github.com/control-toolbox/OptimalControl.jl/tree/187-doc-update vient de la `main` du coup on a perdu les trucs que j'avais modifié dans la branche `up`.

@ocots je viens de faire un merge de `up` (toujours sur le remote) dans #187-doc-update`, ça dit `Already up to date`.

**Comment by ocots** [comment]
En principe il reste le tuto init et le tuto plot.

**Comment by jbcaillau** [comment]
> En principe il reste le tuto init et le tuto plot.

You mean: "all updated *wrt.* plotting changes but `init` et `plot` tutos"?

**Comment by ocots** [comment]
Now I mean that there is only the tutorial on how to initialise to update. 

Of course, if we change again the API, there will be new changes to do. But I have made a pass on all the tutos and they compile with the versions present in the `Project.toml`.

**Comment by ocots** [comment]
This issue is for the update of the `Project.toml` and the documentation taking into account new releases of `CT` packages.

**Comment by ocots** [comment]
The associated branch has been renamed `187-oc-upgrade`.

**Comment by jbcaillau** [comment]
@ocots @PierreMartinon teaser (4x faster load 💙)
![IMG_3290](https://github.com/control-toolbox/OptimalControl.jl/assets/62183989/84f805c0-9d2a-4050-b6a9-0a9d1c752d6b)

**Comment by ocots** [comment]
The documentation of [BifurcationKit](https://bifurcationkit.github.io/BifurcationKitDocs.jl/dev/) is very nice. 

Here is an example of [shooting](https://bifurcationkit.github.io/BifurcationKitDocs.jl/dev/tutorials/ode/Colpitts/#Periodic-orbits-with-Multiple-Standard-Shooting).

**Comment by jbcaillau** [comment]
> The documentation of [BifurcationKit](https://bifurcationkit.github.io/BifurcationKitDocs.jl/dev/) is very nice.
> 
> Here is an example of [shooting](https://bifurcationkit.github.io/BifurcationKitDocs.jl/dev/tutorials/ode/Colpitts/#Periodic-orbits-with-Multiple-Standard-Shooting). See also [this](https://bifurcationkit.github.io/BifurcationKitDocs.jl/dev/periodicOrbit/).

Nice job @rveltz 🙂
