### ISSUE TITLE
CTProblems to OptimalControlBenchmark

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#188]
@ocots 
- remove dependence towards `CTProblems.jl`
- enlarge / generalise towards more or less independent optimal control benchmark

**Comment by ocots** [comment]
Ping @frapac

**Comment by jbcaillau** [comment]
@ocots shorter name: `OptimalControlBenchmark -> OCBenchmark`

**Comment by ocots** [comment]
Even shorter `OCBenchmark -> OCB`.

**Comment by jbcaillau** [comment]
@ocots 
![IMG_3303](https://github.com/control-toolbox/OptimalControl.jl/assets/62183989/2439c2b6-6eee-4aa9-8b8d-8d1abe99fd65)
