### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by ocots** [control-toolbox/OptimalControl.jl#194]
- [x] #195
- [x] @PierreMartinon update tutorial about initialisation 
- [x] @PierreMartinon @ocots add a tutorial on warmstart / discrete continuation
- [x] @jbcaillau add a tutorial manipulating the NLP (reexport `NLP`)
- [x] @jbcaillau add a tutorial on the abstract definition

**Comment by ocots** [comment]
Update the page from `control-toolbox.org`. Review the graphs of dependencies.

**Comment by jbcaillau** [comment]
> * [ ]  @ocots Review the graphs of dependencies

@ocots generate these graphs automatically, useless otherwise

**Comment by ocots** [comment]
Bon la documentation ne se fait pas ! Il y a un seg fault : https://github.com/control-toolbox/OptimalControl.jl/actions/runs/9784151089/job/27014410007

**Comment by PierreMartinon** [comment]
Got the SegFault too, but it kinda disappeared when I uncommented back all the pages...

https://github.com/control-toolbox/OptimalControl.jl/pull/199

**Comment by PierreMartinon** [comment]
Imported basic tutorial for discrete continuation from CTDirect.
https://github.com/control-toolbox/OptimalControl.jl/pull/200

**Comment by PierreMartinon** [comment]
Draft for NLP tutorial, @jbcaillau you can start from there !
https://github.com/control-toolbox/OptimalControl.jl/pull/203

**Comment by jbcaillau** [comment]
> Draft for NLP tutorial, @jbcaillau you can start from there ! #203

🙏🏽🙏🏽🙏🏽

**Comment by jbcaillau** [comment]
Updating Goddard doc:
- using only `OrdinaryDiffEq.jl`
- not using `MINPACK.jl` anymore
