### ISSUE TITLE
Go to general registry 🤞

### ISSUE THREAD

**Issue by ocots** [control-toolbox/OptimalControl.jl#208]
- [x] [TagBot](https://github.com/JuliaRegistries/TagBot)
- [x] [Install app](https://github.com/JuliaComputing/Registrator.jl?tab=readme-ov-file#install-registrator)
- [x] Comment this issue following [this](https://github.com/JuliaComputing/Registrator.jl?tab=readme-ov-file#via-the-github-app)

**Comment by ocots** [comment]
@JuliaRegistrator register()

**Comment by ocots** [comment]
Checkout @PierreMartinon @jbcaillau

**Comment by jbcaillau** [comment]
@ocots @PierreMartinon this is what one would call *passer inaperçu* 😱😅
![IMG_3317](https://github.com/control-toolbox/OptimalControl.jl/assets/62183989/4f7ac4fd-faac-4dd6-bb3c-3e21899dc264)

> Et pour leurs coups d'essai veulent des... heu...

**Comment by PierreMartinon** [comment]
@ocots, @jbcaillau So we'll soon get rid of ct-registry ? If someone keeps it they may stay with out-of-date versions ?

**Comment by ocots** [comment]
There will be no problem.

**Comment by ocots** [comment]
🚀
