### ISSUE TITLE
Go back to MINPACK as NLE solver

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#209]
@ocots very poor solution / efficiency with `NonlinearSolve.jl` compared to `MINPACK.fsolve`. Check, *e.g.*, on Goddard case.

**Comment by ocots** [comment]
But I cannot use `MINPACK` anymore...

**Comment by ocots** [comment]
Have you compared with the Jacobian of the shooting function?

**Comment by ocots** [comment]
I try to speedup Goddard.

**Comment by jbcaillau** [comment]
@ocots OK. But priority = something that passes `x86` tonight.

Right now I will keep `MINPACK` for the orbit transfer case, so I suggest to deactivate `mac os`.

**Comment by ocots** [comment]
macos is also with x86...

**Comment by jbcaillau** [comment]
> macos is also with x86...

Ah. Though you had an issue with `MINPACK` not being recompiled for ARM, but I guess that's only on *your* laptop.

**Comment by ocots** [comment]
> > macos is also with x86...
> 
> Ah. Though you had an issue with `MINPACK` not being recompiled for ARM, but I guess that's only on *your* laptop.

Yes only my laptop.

**Comment by jbcaillau** [comment]
@ocots merge done in #210. we agree that the root package (= `OptimalControl.jl`) must *not* be in `docs/Project.toml` when pushing on the server? (= CI will add it) Although we need it to `make` locally.

**Comment by ocots** [comment]
Yes it must *not* be in the `docs/Project.toml`.

**Comment by jbcaillau** [comment]
@ocots EXCELLENT work for the MRI application 👍🏽👍🏽👍🏽

**Comment by ocots** [comment]
I have changed the tolerances for the nle solver for the goddard application. It reduces the iterations from 15 to 5. Not a big change.

**Comment by jbcaillau** [comment]
If it passes, good. Merging into my branch.
