### ISSUE TITLE
Callback d'affichage au cours des itérations

### ISSUE THREAD

**Issue by control-toolbox** [control-toolbox/OptimalControl.jl#22]
Voir comment ajouter un callback qui permettrait de voir l'évolution de la solution au cours des itérations.

**Comment by control-toolbox** [comment]
Cela pourrait être sympa d'avoir un concept de résolution pas à pas pour pouvoir faire de l'analyse au cours des itérations, modifier des paramètres, etc. L'idée serait d'avoir trois mode d'utilisation des packages :

* basic 
* advanced
* expert

Le mode `basic` concerne l'utilisateur qui veut résoudre un problème en choisissant un algo et des options de base. Il s'intéresse à avoir une solution et puis c'est tout.

Le mode `advanced` concerne l'utilisateur qui veut faire de l'analyse de performance ou de l'analyse des solutions, il doit bien comprendre les différents algos et leurs paramètres.

Le mode `expert` concerne l'utilisateur qui aimerait construire quelque chose de personnalisé en modifiant les paramètres au cours des itérations par exemple, en ajoutant un schéma, une variante, etc.

**Comment by jbcaillau** [comment]
oui, ça relève plutôt de la gestion du solveur en question (on est plutôt end users) ; un callback ad hoc doit en effet faire le job
