### ISSUE TITLE
time_grid non uniforme

### ISSUE THREAD

**Issue by alesiagr** [control-toolbox/OptimalControl.jl#228]
Salut @PierreMartinon ,

Je teste l'option time_grid = vecteur que je veux (time steps non uniforme) dans solve pour la résolution directe, mais ça ne marche pas: 

┌ Warning: time_grid does not seem to be a valid Ipopt option.
└ @ NLPModelsIpopt ~/.julia/packages/NLPModelsIpopt/WBABa/src/NLPModelsIpopt.jl:214
Time: 90, Objective: 895.5360413024483, Iteration: 28

J'ai bien la version Optimal Control 0.9.1

Est-ce que cette fonction est bien existante ?

**Comment by ocots** [comment]
@alesiagr Est-ce que tu peux montrer le fichier où il y a le problème ?

**Comment by PierreMartinon** [comment]
Pareil. Le message indique que l'argument n'a pas ete reconnu par *solve* et a ete transmis tel quel a Ipopt (dans les kwargs), qui ne sait pas quoi en faire :D

**Comment by alesiagr** [comment]
https://github.com/mctao-inria/sail-therm/blob/main/interstellar_sail2D_control_cossin.jl

Voici le ficher, ligne 230 @ocots

**Comment by PierreMartinon** [comment]
Ok, peut-etre verifier la version de CTDirect qui est utilisee.
```]st```
Si CTDirect pointe sur une version locale, elle n'est peut-etre pas a jour. Dans ce cas faire un pull sur main pour recuperer la derniere version, ou bien ```free CTDirect``` pour utiliser la derniere release enregistree.

**Comment by alesiagr** [comment]
@PierreMartinon 

J'ai ça comme versions. 

`(sail-therm) pkg> st
Status `~/sail-therm/Project.toml`
  [a98d9a8b] Interpolations v0.15.1
  [033835bb] JLD2
  [f4238b75] NLPModelsIpopt
  [5f98b655] OptimalControl v0.9.1
  [91a5bcdd] Plots v1.40.5
Warning The project dependencies or compat requirements have changed since the manifest was last resolved. It is recommended to `Pkg.resolve()` or consider `Pkg.update()` if necessary.`


Aussi, 

`ERROR: UndefVarError: `CTDirect` not defined` quand j'essaie _CTDirect.solve_

**Comment by jbcaillau** [comment]
@PierreMartinon any clue on this? do you have an example of passing a `time_grid`? (I can go to tests otherwise.)

**Comment by PierreMartinon** [comment]
@jbcaillau Il y a des exemples dans les tests CTDirect ici: https://github.com/control-toolbox/CTDirect.jl/blob/main/test/test_grid.jl
Mais je ne suis pas sur qu'on ait reteste depuis ControlOptimal. Je vais regarder !

@alesiagr Faire une mise a jour a tout hasard ```]up```.
Et sans doute un ```using CTDirect``` pour tester l'appel *CTDirect.solve*

**Comment by alesiagr** [comment]
Merci @PierreMartinon 

Alors CTDirect a l'air de conflictuel avec OptimalControl, je n'arrive pas à lui filer le initial guess mnt:
`ERROR: TypeError: in keyword argument init, expected OptimalControlInit, got a value of type CTBase.OptimalControlSolution`

**Comment by alesiagr** [comment]
> > Merci @PierreMartinon
> > Alors CTDirect a l'air de conflicter avec OptimalControl, je n'arrive pas à lui filer le initial guess mnt: `ERROR: TypeError: in keyword argument init, expected OptimalControlInit, got a value of type CTBase.OptimalControlSolution`
> 
> Oui, on est en train de preparer une nouvelle version qui corrige ca et quelques autres couacs.

Parfait, merci beaucoup! Est-ce que vous pourriez me faire signer car c'est corrigé, pour que je teste? :)

**Comment by alesiagr** [comment]
Hello @PierreMartinon @ocots !

Est-ce que c'était réglé cette question par tout hasard? :D

**Comment by ocots** [comment]
Je pense qu'il vaut mieux attendre demain. D'ici demain le package sera sur le registre général et donc une nouvelle release sera disponible. En attendant on ne peut pas modifier le code.

**Comment by alesiagr** [comment]
Merci @ocots ! J'attends demain avec impatience :D

**Comment by ocots** [comment]
Nouvelle version `v0.9.4` de `OptimalControl.jl` ! A essayer.

**Comment by alesiagr** [comment]
Ça a l'air de fonctionner, merci !!! :)
