### ISSUE TITLE
Indirect simple shooting method

### ISSUE THREAD

**Issue by control-toolbox** [control-toolbox/OptimalControl.jl#24]
Dans un premier temps, on veut pouvoir faire un appel sous la forme `solve(ocp, :indirect)` pour faire appel à une méthode de tir indirect pour résoudre un `ocp`. Résoudre directement un `ocp` via du tir peut se faire soit : 
* car le problème est régulier et on peut construire le contrôle maximisant, etc.
* car on régularise et on revient au cas d'avant.

Sinon, on peut imaginer vouloir résoudre un `ocp` en donnant plus d'informations : la structure, les hamiltoniens ou les contrôles, etc. Dans ce cas, si par exemple on écrit une fonction de tir à partir du PMP et d'informations supplémentaires, on peut imaginer faire du point de vue de l'utilisateur un `solve(pmp)`. Il faudrait alors définir une méthode `PMP` qui prend en argument ce qu'il faut par exemple. A réfléchir.

**Comment by ocots** [comment]
On peut commencer plutôt par faire un exemple de tir dans le package `PathFollowing` en appelant `NonLinearSolve` dans un premier temps puis en faisant du suivi.

**Comment by jbcaillau** [comment]
✅

**Comment by ocots** [comment]
see later
