### ISSUE TITLE
Update links for JuliaCon 2024 (doc)

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#245]
@joseph-gergaud
> Il y a toujours une erreur 404 lorsque l’on clique sur orbital transfer et Solar sailing sur la présentation de juliacon 24 : 
https://control-toolbox.org/OptimalControl.jl/stable/juliacon2024.html

**Comment by ocots** [comment]
@joseph-gergaud Il faudrait dans HAL mettre des urls avec le numéro de version, comme ça c'est archivé.

Par exemple, pour FGS2024 : https://control-toolbox.org/OptimalControl.jl/v0.9.2/fgs-2024.html

Pour JuliaCon2024 : https://control-toolbox.org/OptimalControl.jl/v0.9.2/juliacon2024.html

JuliaCon 2023 : https://control-toolbox.org/OptimalControl.jl/v0.8/juliacon2023.html

JuliaOpt 2023 : https://control-toolbox.org/OptimalControl.jl/v0.8/juliaopt2023.html

**Comment by jbcaillau** [comment]
@gergaud links form JuliaCon 2024 tab corrected by https://github.com/control-toolbox/OptimalControl.jl/pull/257 (waiting for @ocots to merge), closing this issue. you can keep track of the post [above](https://github.com/control-toolbox/OptimalControl.jl/issues/245#issuecomment-2252268726) to update HAL links 👍🏽
