### ISSUE TITLE
Use Inria runners for GitHub actions

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#247]
See email exchange with @j-l-s (July 23, 2024)

**Comment by jbcaillau** [comment]
Still we would need to check whether the performance of the runners is the same as with GitHub runners

**Comment by jbcaillau** [comment]
Contacted sergen.canziz@inria.fr ✅

**Comment by jbcaillau** [comment]
@ocots @PierreMartinon @gergaud fruitful exchange with @srcansiz and @j-l-s today. meeting scheduled Aug. 26 9:00 to try to deploy on a test repo (maybe not OptimalControl.jl but a subpackage - CTBase.jl...)
https://inria.webex.com/meet/jean-baptiste.caillau

Retex from another Inria project: Inria self-hosted runners (= the slaves we used during the ADT) should be faster than those from GitHub 🤞🏾

**Comment by j-l-s** [comment]
I do not have access to the `Settings` page of CTBase (or any other) repo, to create a new self hosted runner.
Do I have the correct access rights  to the organisation/repos ?

**Comment by ocots** [comment]
> I do not have access to the `Settings` page of CTBase (or any other) repo, to create a new self hosted runner. Do I have the correct access rights to the organisation/repos ?

Should be ok now.

**Comment by j-l-s** [comment]
Not really: I would like to add a Runner to the organisation (control-toolbox), so it can be shared with all repositories. It need "Owner" credentials for it.. 

PS: I have access to  `https://github.com/control-toolbox/CTBase.jl/settings`, but no menu "Runners" on this page...
PPS: not emergency for that, I just wanted to anticipate the meeting with JBC

**Comment by jbcaillau** [comment]
Full power entrusted, mr Sz 😱

**Comment by j-l-s** [comment]
Instead of exchanging in this issue, I started a conversation here: https://github.com/orgs/control-toolbox/discussions/59

**Comment by PierreMartinon** [comment]
There seems to be an issue for the TagBot workflow when launched on the inria runner: missing docker ?

https://github.com/control-toolbox/CTDirect.jl/actions/runs/10562569660/job/29260837620
