### ISSUE TITLE
Display optimal control problem

### ISSUE THREAD

**Issue by control-toolbox** [control-toolbox/OptimalControl.jl#25]
* Améliorer affichage du problème ocp : text/html ou markdown ou latex.
* Pour les plots, on peut utiliser `recipe` il me semble au lieu de `plot` directement. A voir.

**Comment by control-toolbox** [comment]
Pour les plots, on peut utiliser `recipe` il me semble au lieu de `plot` directement. A voir.

**Comment by ocots** [comment]
En ce moment, le print sur un `OptimalControlModel` ne fonctionne pas.

**Comment by ocots** [comment]
> En ce moment, le print sur un `OptimalControlModel` ne fonctionne pas.

C'est bon ceci est réglé.
