### ISSUE TITLE
Gestion des solutions

### ISSUE THREAD

**Issue by control-toolbox** [control-toolbox/OptimalControl.jl#26]
Pour la gestion des solutions voir par exemple ici : https://github.com/SciML/SciMLBase.jl/blob/master/src/solutions/ode_solutions.jl

**Comment by ocots** [comment]
Pour les problèmes c'est ici : https://github.com/SciML/SciMLBase.jl/tree/master/src/problems

**Comment by ocots** [comment]
Voir aussi [Issue 12](https://github.com/control-toolbox/control-toolbox.github.io/issues/12)

**Comment by jbcaillau** [comment]
Intéressant, cf. par exemple gestion du `isinplace`. On peut pas tout faire d’emblée à ce niveau de `Julia`, mais c’est pas l’idée. Tu vois comment est défini le type fonctionnel `F` ?

**Comment by ocots** [comment]
Pour `isinplace` : https://github.com/SciML/SciMLBase.jl/blob/master/src/utils.jl#L211

Voir aussi ```nargs = numargs(f)``` qui peut servir par exemple pour savoir si la dynamique est autonome ou non.

**Comment by ocots** [comment]
Pour le type fonctionnel, voir par exemple : 

*[AbstractODEFunction](https://github.com/SciML/SciMLBase.jl/blob/1aa5aacc8e7c45d3542cec7950b69c6fc07b7425/src/scimlfunctions.jl#L209)
* [ODEFunction type](https://github.com/SciML/SciMLBase.jl/blob/1aa5aacc8e7c45d3542cec7950b69c6fc07b7425/src/scimlfunctions.jl#L393)
* [ODEFunction constructor](https://github.com/SciML/SciMLBase.jl/blob/1aa5aacc8e7c45d3542cec7950b69c6fc07b7425/src/scimlfunctions.jl#L2149)
* [specialize](https://github.com/SciML/SciMLBase.jl/blob/1aa5aacc8e7c45d3542cec7950b69c6fc07b7425/src/scimlfunctions.jl#L295)

Il y a par moment le type `Any` qui est utilisé, sinon il utilise beaucoup ces types à lui qui encapsulent une fonction dans une structure avec des informations supplémentaires permettant d'accélérer la résolution du problème par la suite. Il semblerait que si on a la jacobienne par exemple, on peut utiliser le constructeur de la fonction pour fournir la jacobienne.

**Comment by ocots** [comment]
C'est en cours...
