### ISSUE TITLE
Add functional syntax to the time minimisation problem

### ISSUE THREAD

**Issue by ocots** [control-toolbox/OptimalControl.jl#279]
Would it be possible to add the functional syntax also to the time minimisation problem?
Many thanks

_Originally posted by @paolo-mgi in https://github.com/control-toolbox/OptimalControl.jl/issues/264#issuecomment-2276880177_

**Comment by ocots** [comment]
Added for the next release.

**Comment by paolo-mgi** [comment]
Great, thanks again.
