### ISSUE TITLE
doc update: @def new syntax

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#284]
update at least: 
- abstract doc
- basic examples

**Comment by ocots** [comment]
Need a new release and let's go.

**Comment by jbcaillau** [comment]
Done after this fix https://github.com/control-toolbox/CTBase.jl/pull/234

**Comment by jbcaillau** [comment]
> Need a new release of `CTBase.jl` and let's go.

@ocots and new releases of `OptimalControl`,  `CTDirect` and `CTFlow` as well (pinned CTBase `0.11.0`)

**Comment by ocots** [comment]
> > Need a new release of `CTBase.jl` and let's go.
> 
> @ocots and new releases of `OptimalControl`,  `CTDirect` and `CTFlow` as well (pinned CTBase `0.11.0`)

`CTDirect.jl` and `CTFlows.jl` pin `CTBase.jl 0.12` so it's ok. For `OptimalControl.jl` we are making the new release which pin also `0.12`.

**Comment by jbcaillau** [comment]
@ocots my mistake. yes, only OptimalControl current tag not up to date

**Comment by jbcaillau** [comment]
@ocots doc build still quite long, we might need to move these tutos in one / several external repos:
```julia
        "Tutorials" => [
            "tutorial-continuation.md",
            "Goddard: direct, indirect"  => "tutorial-goddard.md",
            "tutorial-iss.md",
            "Linear–quadratic regulator" => "tutorial-lqr-basic.md",
            "tutorial-nlp.md",
```
