### ISSUE TITLE
Review of the documentation

### ISSUE THREAD

**Issue by ocots** [control-toolbox/OptimalControl.jl#293]
@jbcaillau Actually, I use sometimes the backquote when naming a package, sometimes I put the suffix `.jl` and sometimes I do the contrary. We should fix the syntax:

- `OptimalControl.jl` or `OptimalControl` or OptimalControl.jl or OptimalControl?
- [`OptimalControl.jl`](https://control-toolbox.org/OptimalControl.jl) or [`OptimalControl`](https://control-toolbox.org/OptimalControl.jl) or [OptimalControl.jl](https://control-toolbox.org/OptimalControl.jl) or [OptimalControl](https://control-toolbox.org/OptimalControl.jl)?
- When we name a function/method: 
    - `solve` or solve? 
    - [`solve`](https://control-toolbox.org/OptimalControl.jl/stable/api-optimalcontrol.html#CommonSolve.solve-Tuple{OptimalControlModel,%20Vararg{Symbol}}) or [solve](https://control-toolbox.org/OptimalControl.jl/stable/api-optimalcontrol.html#CommonSolve.solve-Tuple{OptimalControlModel,%20Vararg{Symbol}})?

What is the rule?

**Comment by jbcaillau** [comment]
@ocots good point. I think the usage is rather, check [SciML doc](https://docs.sciml.ai/Overview/stable/getting_started/find_root), *e.g.*

> @jbcaillau Actually, I use sometimes the backquote when naming a package, sometimes I put the suffix `.jl` and sometimes I do the contrary. We should fix the syntax:
> 
> * ~~`OptimalControl.jl` or `OptimalControl` or ~~ OptimalControl.jl ~~or OptimalControl?~~
> * ~~[`OptimalControl.jl`](https://control-toolbox.org/OptimalControl.jl) or [`OptimalControl`](https://control-toolbox.org/OptimalControl.jl) or~~ [OptimalControl.jl](https://control-toolbox.org/OptimalControl.jl) ~~or [OptimalControl](https://control-toolbox.org/OptimalControl.jl)?~~
> * When we name a function/method:
>   
>   * `solve` ~~or solve?~~
>   * [`solve`](https://control-toolbox.org/OptimalControl.jl/stable/api-optimalcontrol.html#CommonSolve.solve-Tuple%7BOptimalControlModel,%20Vararg%7BSymbol%7D%7D) ~~or [solve](https://control-toolbox.org/OptimalControl.jl/stable/api-optimalcontrol.html#CommonSolve.solve-Tuple%7BOptimalControlModel,%20Vararg%7BSymbol%7D%7D)?~~
