### ISSUE TITLE
Formulation of the control problem by the user

### ISSUE THREAD

**Issue by control-toolbox** [control-toolbox/OptimalControl.jl#30]
Use of macros as JuMP instead of functions?

See https://docs.sciml.ai/ModelingToolkit/stable/systems/OptimizationSystem/

**Comment by control-toolbox** [comment]
https://docs.sciml.ai/ModelingToolkit/stable/systems/OptimizationSystem/

**Comment by control-toolbox** [comment]
On peut aussi le faire de manière itérative avec des fonctions (pas en symbolique). Il faut donc pouvoir de manière incrémentale modifier le problème de contrôle optimal. C'est dans le solve que l'on définit le bon type de problème.

**Comment by control-toolbox** [comment]
Voir https://github.com/SciML/ModelingToolkit.jl

**Comment by jbcaillau** [comment]
@ocots Oui, faisons en deux temps : 
- fonctionnel (on sait faire)
- abstrait (= symbolique, aussi proche que possible de la description math)

**Comment by jbcaillau** [comment]
foo

**Comment by ocots** [comment]
C'est en cours, cette issue est obsolète.
