### ISSUE TITLE
Add pure constraints

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#63]
- [x] add pure state constraints (vs. mixed ones)

$$ c_l \leq c(t, x(t)) \leq c_u $$

- [ ] update Goddard case accordingly

See also [this issue](https://github.com/control-toolbox/OptimalControl.jl/issues/64)

**Comment by PierreMartinon** [comment]
@jbcaillau 
This is actually useful for the direct method too: if we want to enforce the state constraints c(x_f) while we don't necessarily have a corresponding control u_f, for instance if discretizing with an explicit Euler formula. Use case: goddard example with final mass constraint.

**Comment by jbcaillau** [comment]
@ocots @PierreMartinon @joseph-gergaud closing this issue that is subsumed by [sss](https://github.com/control-toolbox/OptimalControl.jl/issues/115#issuecomment-1460627241) #115
