### ISSUE TITLE
Allow autonomous and non-autonomous problem description

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#64]
- an ocp can autonomous or not, *i.e.* functions defining can (all) depend on time or not
- current version (ADT sprint no. 6) is autonomous
- [ ] add something like
```julia
ocp = Model{:nonautonomous}(…)
```
to enforce definitions depending on time

**Comment by ocots** [comment]
J'ai ajouté la gestion du cas autonome et non autonome au niveau de la création du modèle et ensuite pour la fonction de Lagrange et la dynamique. A voir s'il faut gérer aussi les contraintes de cette façon.

**Comment by jbcaillau** [comment]
Super

- oui, il faut faire pareil pour la définition complète du problème. C'est transparent car parsé au niveau abstrait, mais à traiter explicitement au niveau fonctionnel
- dès qu'un temps apparaît qqpart, le pb devient non-autonome (il faut une cohérence, *i.e.* du t partout ou nulle part)
- on poursuit pour commencer une version ocp autonome

**Comment by ocots** [comment]
Je pense que c'est ok pour l'ensemble du problème, contraintes incluses.
