### ISSUE TITLE
Scalar / vector control / state

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#68]
- as a user, I want to define (both in abstract and functional settings) a scalar state / control and write, *e.g.*, `x` instead of `x[1]`
- [x] treat vector controls
- [x] treat scalar states

**Comment by ocots** [comment]
Mettre les problèmes `basic` et `goddard` en vectoriel sur le contrôle.

**Comment by jbcaillau** [comment]
@ocots j’ai l’impression que les deux points ci-avant sont faits. je rajoute une question similaire dans le cas des contraintes d’état (pures ou mixtes) qui peuvent, a priori, être vectorielles (de même, du coup, que le multiplicateur). dans [flow.jl](https://github.com/control-toolbox/OptimalControl.jl/blob/main/src/flows.jl) ça passe en scalaire ou vectoriel, nickel ; c’est bien que le user n’ait pas à se poser la question (= le code en fonctionnel doit être le même que la contrainte soit scalaire ou non).

```julia
function H(f::Function, u::Function, μ::Function, c::Function)
    return (x, p) -> p'*f(x,u(x,p)) + μ(x,p)'*c(x,u(x,p))
end
```

De fait, c’est assez rare d’avoir plusieurs contraintes sur l’état actives simultanément mais bon.

**Comment by ocots** [comment]
> 

Ce sera gérer en interne. Le user ne voit rien en principe.
