### ISSUE TITLE
Solution plot

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#69]
- [x] for Lagrange and Bolza costs, that is internally transformed into a Mayer problem, as a user I want to see a plot of the cost not as an additional (= $n+1$ -th) state but as a specific coordinate 
- [x] plot control *below* (an not side by side with) state and adjoint

**Comment by ocots** [comment]
Make a general plot working for Direct and DirectShooting Solutions. For that, we need a general plot with getters.

**Comment by PierreMartinon** [comment]
- Done: plot state then costate below then control below, ie 'rows' layout. The code for 'columns' layout is just commented, probably it is best to use an option to choose between rows, columns and the one done by Olivier for large dimensions ie all variables collapsed on same graph.
- Done: do not plot the additional state in the case of a Mayer -> Lagrange transformation. The numerical value of the objective is returned by the accessor objective(sol). It could be printed by defaut in the title of the plot or something ?

**Comment by ocots** [comment]
Define an `OptimalControlSolution` with function of time? See [discussion](https://github.com/orgs/control-toolbox/discussions/15#discussioncomment-4973511).

**Comment by jbcaillau** [comment]
👍🏽 merci @PierreMartinon, je teste ça
