### ISSUE TITLE
Use assert macro to check assertions

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#74]
https://docs.julialang.org/en/v1/manual/metaprogramming/#Building-an-advanced-macro

![B4CF5E63-C863-4F7F-AF97-745A589B6075](https://user-images.githubusercontent.com/62183989/216677904-f240e030-2b3c-4bc0-b776-de7e8d95e4d1.jpeg)

**Comment by PierreMartinon** [comment]
Keep in mind that assert can be disabled by some optimization options, so it should be used as a debugging tool
https://docs.julialang.org/en/v1/base/base/#Base.@assert

**Comment by jbcaillau** [comment]
Right, just the way it has to be 👍🏽
