### ISSUE TITLE
Flow concatenation

### ISSUE THREAD

**Issue by control-toolbox** [control-toolbox/OptimalControl.jl#78]
@ocots 
- add rhs field to the flow to redefine (with an `if`…) the rhs and integrate it properly when concatenating
- add event detection

[See also](https://stackoverflow.com/questions/60321301/user-defined-infix-operator)

**Comment by ocots** [comment]
Work in progress [here](https://github.com/control-toolbox/HamiltonianFlows.jl/blob/concatenate/src/concatenation.jl).
